baseURL = "https://ninthday.github.io/"
languageCode = "en-us"
title = "Ninthday"
theme = "m10c"
paginate = 5

[params]
  author = "Tuvix Shih (ninthday)"
  description = "ninthday.dev"
  [[params.social]]
    name = "github"
    url = "https://github.com/ninthday"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/JeffyShih"
  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    primaryColor = "#ffffff"
    lightColor = "#a2a2a2"
    lightestColor = "#d3d3d3"
